name: oysloe_mobile
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  responsive_sizer: ^3.3.1
  google_fonts: ^6.2.1
  flutter_native_splash: ^2.4.4
  go_router: ^16.1.0
  flutter_svg: ^2.2.0
  lottie: ^3.1.2
  flutter_chat_ui: ^2.9.0
  uuid: ^4.5.1
  flutter_chat_types: ^3.6.2
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0


flutter:
  uses-material-design: true

  assets:
    - assets/gifs/
    - assets/json/
    - assets/images/
    - assets/icons/

 
